language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.1.1
  - jruby-19mode
  - rbx-2.1.1
jdk:
  - oraclejdk7
  - openjdk7
matrix:
  exclude:
    - rvm: 1.9.2
      jdk: openjdk6
    - rvm: 1.9.2
      jdk: openjdk7
    - rvm: 1.9.2
      jdk: oraclejdk7
