---
cypher:
  descriptors:
  - name: Appealing
    description:
    effects:
      pool_mods:
        intellect: 2
      trained_skills: []
      inabilities: []
  - name: Brash
    description:
    effects:
      pool_mods:
        speed: 2
      trained_skills: []
      inabilities: []

