---
demographics:
  census_fields:
  - field: name
    width: 28
    title: Name
  - field: demographic
    width: 10
    title: Gender
    value: gender
  - field: group
    width: 20
    title: Faction
    value: Faction
  - field: group
    width: 20
    title: Position
    value: Position
  demographics:
  - actor
  - hair
  - eyes
  - skin
  - height
  - physique
  - nationality
  - fullname
  - gender
  - birthdate
  - callsign
  - position
  disable_auto_shortcuts: false
  editable_properties:
  - fullname
  - hair
  - physique
  - callsign
  groups:
    Faction:
      desc: Game Group Primarily Associated With
      values:
        Shield: All members of SHIELD
        Wingnuts: Active Duty Air Force.
        Guardians: Vanguard Industries Employees
        Townies: Rose Hill Civilians of all types that aren't a member of the other
          factions
  help_text:
    actor: See 'help actors'.
    physique: Build/body type - athletic, wiry, slim, pudgy, etc.
    gender: Male/Female/Other
    hair: Hair color
    eyes: Eye color
    skin: Complexion
    birthdate: Specify a date mm/dd/yyyy or use %xcage <years>.%xn
    callsign: Callsign for pilots.  Non-pilots may leave blank or enter a nickname.
  max_age: 90
  min_age: 18
  nickname_field: ''
  nickname_format: "%{name} (%{nickname})"
  required_properties:
  - actor
  - hair
  - eyes
  - skin
  - height
  - physique
  - nationality
  - fullname
  - gender
  - birthdate
  shortcuts:
    groups: group
    colonies: group colony
    demographics: demographic
