help:
    categories:
        main:
            command: help
            title: "Player Help"
        admin:
            command: ahelp
            title: "Admin Help"
            roles: ["admin"]
            